CREATE DATABASE TenderHire;
CREATE TABLE Customers(UserID BIGINT NOT NULL AUTO_INCREMENT, Email VARCHAR(50) NOT NULL, Username VARCHAR(50) NOT NULL, Password VARCHAR(50) 
	NOT NULL,IMAGE,  PRIMARY KEY(UserID));
CREATE TABLE Supliers(UserID BIGINT NOT NULL AUTO_INCREMENT, Email VARCHAR(50) NOT NULL, Username VARCHAR(50) NOT NULL, Password VARCHAR(50) 
	NOT NULL, PRIMARY KEY(UserID));
create table TenderDetails(TenderId BIGINT NOT NULL AUTO_INCREMENT, Company VARCHAR(50) NOT NULL, Country VARCHAR(20) NOT NULL, Tender VARCHAR(30) NOT NULL, Category VARCHAR(30) NOT NULL, Bid INT(15) NOT NULL, PRIMARY KEY(TenderId));

create table Users
